### ISSUE TITLE
Some long header names in *-taxa.txt are not mapped to shorter names

### ISSUE THREAD

**Issue by yjkiwilee** [WFO-ID-pilots/text2matrix#1]
In *\*-taxa.txt*, the following long header names are not mapped to shorter names.

http://rs.tdwg.org/dwc/terms/kingdom
http://rs.tdwg.org/dwc/terms/nomenclaturalCode
http://purl.org/dc/terms/bibliographicCitation
http://purl.org/dc/terms/rightsHolder
http://purl.org/dc/terms/license
http://purl.org/dc/terms/rights

These may be manually added into the mapper.

**Comment by nickynicolson** [comment]
Yes these are the ones that are specified as having default values in the meta.xml - find to add them manually
